task: textcat
ndata: -1
niter: 10
nbatch: 16
scheduler: false
test_size: 0.1
data: ~/datasets/ldcc.jsonl
label:
label_json: ~/datasets/ldcc_labels.json
lang: mecab
pretrained:
neval: -1
freeze: false
weights:
name:
