default_language_version:
    python: python3.7

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-symlinks
    - id: flake8
      exclude: scripts/

- repo: git@github.com:humitos/mirrors-autoflake.git
  rev: v1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
    - id: isort

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
