[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[versionup]
files = "camphr/VERSION.py"
tag = true
commit = true

[tool.poetry]
version = "0.5.0.dev2"
name = "camphr"
authors = [ "tamuhey <tamuhey@gmail.com>",]
description = "spacy plugin"

[tool.poetry.dependencies]
python = ">=3.6.1"
fire = "*"
typing-extensions = "*"
pyyaml = "*"
pyahocorasick = "*"
catalogue = "*"
cytoolz = "*"
more-itertools = "*"
overrides = "*"
scikit-learn = "^0.22"
transformers = "^2.3.0"
pytokenizations = "^0.2.0"
spacy = "^2.2.3"

[tool.poetry.extras]
all = [ "allennlp", "Cython", "mojimoji2", "pyknp", "mecab-python3",]
allennlp = [ "allennlp",]
juman = [ "Cython", "mojimoji2", "pyknp",]
mecab = [ "mecab-python3",]

[tool.poetry.dev-dependencies]
isort = "*"
pylint = "*"
pytest = "*"
flake8 = "*"
pyyaml = "*"
rope = "*"
hypothesis = "*"
pre-commit = "*"
pandas = "*"
hydra-core = "*"
toml = "^0.10.0"

[tool.poetry.dependencies.allennlp]
git = "https://github.com/allenai/allennlp"
rev = "b8fdc9c988e0fbb73acd73205c4c464f8cf5a9c3"
optional = true

[tool.poetry.dependencies.Cython]
version = "*"
optional = true

[tool.poetry.dependencies.mojimoji2]
version = "*"
optional = true

[tool.poetry.dependencies.pyknp]
git = "https://github.com/ku-nlp/pyknp"
branch = "master"
optional = true

[tool.poetry.dependencies.mecab-python3]
version = "^0.996.3"
optional = true

[tool.poetry.dev-dependencies.black]
version = "*"
allow-prereleases = true

[tool.poetry.plugins.spacy_languages]
ja_juman = "camphr.lang.juman:Japanese"
ja_mecab = "camphr.lang.mecab:Japanese"
sentencepiece = "camphr.lang.sentencepiece:SentencePieceLang"
ja_juman_torch = "camphr.lang.juman:TorchJapanese"
ja_mecab_torch = "camphr.lang.mecab:TorchJapanese"
sentencepiece_torch = "camphr.lang.sentencepiece:TorchSentencePieceLang"
