version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  build:
    machine: 
      docker_layer_caching: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: login
          command: echo "$dockerhub_password" | docker login --username $dockerhub_username --password-stdin

      - run: mkdir data
      - aws-s3/sync:
          from: 's3://bedoner/data'
          to: data
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION

      - run:
          name: run pytest
          command: docker-compose run ner pytest
