version: 
jobs:
  build:
    machine: 
      docker_layer_caching: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: build image
          command: |
            echo "$dockerhub_password" | docker login --username $dockerhub_username --password-stdin
            docker build -t ner .

      - run:
          name: run flake8
          command: docker run bedore/nlp-modules:${CIRCLE_SHA1} flake8 .

      - run:
          name: run tests
          command: docker run bedore/nlp-modules:${CIRCLE_SHA1} pytest
      
      - run:
          name: push base image
          command: |
            docker push bedore/nlp-modules-base
            docker push bedore/nlp-modules:${CIRCLE_SHA1}
