name: test extras

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extras: [mecab, juman, udify, elmo]
    steps:
    - uses: actions/checkout@v1
    - run: docker-compose up --exit-code-from ${{ matrix.extras }} ${{ matrix.extras }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

